### ISSUE TITLE
GitHub: Commits signés SocialGroovyBot

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#142]
Voir comment signer les commits de semantic-release

https://github.com/semantic-release/git#gpg-signature

Des secrets GPG ont été déposés au niveau de l'orga pour tester

Voir si possible également de signer les images docker (notary?)

remonté par @lsagetlethias

https://github.com/crazy-max/ghaction-import-gpg#sign-commits

**Comment by lsagetlethias** [comment]
Côté `semantic-release` voici la marche employée côté Archimail :

Comme décrit dans les différents commentaires, il faudrait vérifier le contenu des secrets qui ne match pas avec l'email de la clef GPG.  

`.github/workflows/release.yml`
```yml
env:
  # the email set in secret seems to be wrong (?) so I forced the email manualy
  # GIT_* envs are used by "@semantic-release/git"'s commits
  # but "semantic-release" tag don't use any git env vars, so default registered email and name in GPG key are used.
  GIT_AUTHOR_EMAIL: socialgroovybot@fabrique.social.gouv.fr
  GIT_AUTHOR_NAME: SocialGroovyBot
  GIT_COMMITTER_EMAIL: socialgroovybot@fabrique.social.gouv.fr
  GIT_COMMITTER_NAME: SocialGroovyBot
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        # setup node as you want
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.SOCIALGROOVYBOT_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.SOCIALGROOVYBOT_GPG_PASSPHRASE }}
          git_user_signingkey: true
          # for @semantic-release/git
          git_commit_gpgsign: true
          # no signed push as it's not supported by github 
          git_push_gpgsign: false
          # for semantic-release first tag
          git_tag_gpgsign: true
      - name: Semantic Release
        # semantic-release must be a project (dev)dependency
        run: |
          export PATH="$(pwd)/.github/bin/:$PATH"
          yarn semantic-release
```
Utiliser l'action `cycjimmy/semantic-release-action@v2` est surement faisable en modifiant le PATH directement dans l'env de la step mais il faudrait accéder au pwd.  
Peut-être cette config marcherait, mais je ne l'ai pas testée :
```yml
- name: Semantic Release
  uses: cycjimmy/semantic-release-action@v2
  with:
    extra_plugins: |
      @semantic-release/changelog
      @semantic-release/git
  env:
    PATH: $PWD/.github/bin/:$PATH
```


---
`semantic-release` et leurs plugins utilisent la library `execa` en interne pour exécuter git. Elle a la particularité de target directement les binaires du PATH. Un alias n'est donc pas possible car c'est `/usr/bin/git` qui est appelé et non `git` simplement.  
Il faut donc override et wrap le bin de git. Ci après, le wrapper permet de forcer la signature pour les commits et tag. Pour les tags, on doit faire attention de ne pas être en mode "list" (e.g. `git tag --merged`) => TODO: gérer un appel à `git tag` sans option, qui est un mode "list".  
Dans tous les autres cas, on redirige simplement vers le bin de base de git. (TODO: gérer un emplacement différent du binaire, e.g. custom install)  

`.github/bin/git`
```sh
#!/bin/bash
# if "commit" or "tag" are called, force sign
if [[ "$1" == "commit" && "$@" != *" -S"* ]]; then
    shift 1
    command /usr/bin/git commit -S "$@"
elif [[ "$1" == "tag" && "$@" != *" -s"* ]]; then
    # avoid tag listing options
    if [[
        "$@" != *"--column"* &&
        "$@" != *"--contains"* &&
        "$@" != *"--merged"* &&
        "$@" != *"--no-merged"* &&
        "$@" != *"--sort"* &&
        "$@" != *"--points-at"* &&
        "$@" != *"--format"* &&
        "$@" != *"--color"* &&
        "$@" != *"--ignore-case"* &&
        "$@" != *"--i "*
    ]]; then
        shift 1
        if [[ "$@" != *" -m"* ]]; then
            command /usr/bin/git tag -s -m "Signed tag" "$@"
        else
            command /usr/bin/git tag -s "$@"
        fi
    fi
else
    command /usr/bin/git "$@"
fi

```

Pour rappel, les nouveaux secrets ajoutés en global :
- `SOCIALGROOVYBOT_GPG_PRIVATE_KEY` : clé privée utilisable pour register dans un gpg-client
- `SOCIALGROOVYBOT_GPG_PUBLIC_KEY` : clé public utilisable pour register **manuellement** dans un gpg-client (cf. https://github.com/semantic-release/git#gpg-signature - normalement inutile avec l'action de crazy-max)
- `SOCIALGROOVYBOT_GPG_PASSPHRASE` : phrase de passe pour valider la signature et l'identité
- `SOCIALGROOVYBOT_GPG_KEY_ID` : clé courte d'identification à utiliser en cas de configuration manuelle du param git `user.signingkey`


---

Si jamais pour une raison ou une autre vous avez besoin d'effectuer un import manuel de la clé GPG, voici une marche à suivre potentielle :
```yml
- name: Import GPG key
    run: |
      echo '${{ secrets.SOCIALGROOVYBOT_GPG_PUBLIC_KEY }}' > /tmp/git_gpg_keys.asc # could maybe use env var directly to avoid loading stdout
      echo '${{ secrets.SOCIALGROOVYBOT_GPG_PRIVATE_KEY }}' >> /tmp/git_gpg_keys.asc
      chmod 600 /tmp/git_gpg_keys.asc
      gpg --batch --yes --import /tmp/git_gpg_keys.asc
      echo '#! /bin/bash' > /tmp/gpg-with-passphrase
      echo -n "$(which gpg) --pinentry-mode loopback --passphrase '$SOCIALGROOVYBOT_GPG_PASSPHRASE' --no-tty " >> /tmp/gpg-with-passphrase # -n = no new line for the next "echo" to works properly ; also quoted and env-ed because the passphrase could contains special chars like "$"
      echo '"$@"' >> /tmp/gpg-with-passphrase # prevent interpreting "$@" and render it as is for the bin
      chmod +x /tmp/gpg-with-passphrase # can be more secure if needed
      git config --global user.signingKey "${{ secrets.SOCIALGROOVYBOT_GPG_KEY_ID }}"
      git config --global commit.gpgSign true
      git config --global tag.gpgSign true
      git config --global push.gpgSign false
      git config --global gpg.program /tmp/gpg-with-passphrase
    env:
      SOCIALGROOVYBOT_GPG_PASSPHRASE: ${{ secrets.SOCIALGROOVYBOT_GPG_PASSPHRASE }}
```
