### ISSUE TITLE
falco: reduce noise

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#402]
Pour limiter le bruit induit par les builds, on pourait ajotuer cette exception ?

```yaml
  exceptions:
  - name: kontinuous_buildkit
    fields: [container.image.repository]
    comps: [=]
    values:
      - [docker.io/moby/buildkit]
```

On a plus d'accès à falco ?
