### ISSUE TITLE
secretgen-controller

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#448]
Suite aux [modifs de Jo](https://github.com/carvel-dev/secretgen-controller/pull/376), on aimerait remplacer kubed par [secretgen-controller](https://github.com/carvel-dev/secretgen-controller) pour distribuer les secrets dans les NS de review de manière plus sécurisée

Une fois cet opérateur en place, nous aurons besoin d'avoir en plus une CRD `SecretExport` dans chaque NS de CI. (qui déclarera quels secrets pourront être envoyés où)

Cela permettra de ne plus avoir a copier les secrets lors de la création d'un nouveau NS de review

**Comment by igorrenquin** [comment]
Attente update @devthejo pour publication de la release

**Comment by matmut7** [comment]
Autre alternative Kyverno ?

**Comment by revolunet** [comment]
Exemple avec kyverno (fichier pouvant etre généré avec rancher):

```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-secrets
  annotations:
    policies.kyverno.io/title: Sync CI Secrets
    policies.kyverno.io/category: SRE
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/description: >-
      Copy secrets from ci-namespace to new rancher namespace
spec:
  rules:
    - name: sync-fabrique-secrets-ovh-dev
      match:
        any:
          - resources:
              kinds:
                - Namespace
              operations:
                - CREATE
              annotations:
                field.cattle.io/projectId: c-m-97jxtvnv:p-nk5g5
      generate:
        namespace: "{{request.object.metadata.name}}"
        synchronize: true
        cloneList:
          namespace: ci-fabrique
          kinds:
            - v1/Secret
```
