### ISSUE TITLE
pg_dump CNPG + storages OVH

### ISSUE THREAD

**Issue by revolunet** [SocialGouv/support#450]
Objectif : pouvoir produire des `.sql.gz` réguliers des bases CNPG déployées en plus des backups builtins.

 - [x] dans kontinuous : gérer les backups CNPG
 - [x] dans [helm-chart cnpg-cluster](https://github.com/SocialGouv/helm-charts/tree/main/charts/cnpg-cluster) : gérer les backups CNPG
 - [x] dans kontinuous : en prod, dumper les backups CNPG dans le storage `startup-backups/CNPG-NAME` mis a dispo par `infra-startup` (dossiers "wals" et "base"). [PR](https://github.com/SocialGouv/kontinuous/pull/379)
 - [x] Ajouter un `CronJob` paramétrable dans le [helm-chart cnpg-cluster](https://github.com/SocialGouv/helm-charts/tree/main/charts/cnpg-cluster)
 - [x] dans kontinuous : activer le `CronJob` en prod (et en option, ex preprod)

Au final dans le storage :

```yaml
storage startup-backup:
   cnpg-xxx:
     wals:
     base:
     snapshots:
       db-hasura-YYYYMMDD-HHMMSS.psql.gz
       db-metabase-YYYYMMDD-HHMMSS.psql.gz
```

Notes :
 - trouver une solution pour ne pas exposer le secret du storage dans le NS applicatif (cronjob dans `ci-*`?)

**Comment by revolunet** [comment]
Pour les params du chart pg de kontinuous ca pourrait être :

```yaml
backup:
    ~tpl~enabled: "{{ if .Values.global.isProd }}true{{else}}false{{end}}"
    secretName: fabrique-dev-backups-access-key
    schedule: "0 0 0 * * *" # daily
    retentionPolicy: 60d
    destinationPath: s3://fabrique-dev-backups-access-key/backups
    endpointURL: https://s3.gra.io.cloud.ovh.net
    s3Credentials:
      accessKeyId: true
      region: true
      secretAccessKey: true
      inheritFromIAMRole: false
```
