### ISSUE TITLE
feat(egapro): déploiement

### ISSUE THREAD

**Issue by yohanboniface** [SocialGouv/support#49]
Objectif: essayer de trouver un fonctionnement qui engendre le moins de friction à la fois pour les devs et pour l'équipe SRE.

Idée générale: back et front ont leur propre repository, ils sont responsable de générer des images; le déploiement est sur un repository dédié, il va consommer ces images

Sur front et back:
- on ne génère une image que sur un tag git

Sur deploy:
- on configure les instances qu'on veut déployer, avec un fichier ede configuration du genre:

```yml
prod:
  env:
        EGAPRO_SECRET: XxxxX
  ref:
      api: 2020.06.24
      client: 2020.06.21
staging:
  env:
        EGAPRO_SECRET: XxxxY
  ref:
      api: master
      client: master
killing-feature-top:
  env:
        EGAPRO_SECRET: XxxxZ
  ref:
      api: killing-feature-top
      client: killing-feature
```

Suggestion annexe: est-ce que les images peuvent être générées via les "ref" git par le repository de déploiement, dès lors qu'on les demande pour un environnement ?

Questions en suspens:
- comment tourner les migrations one-shot sur les environnements en gardant une boucle de rétroaction rapide ?
- idem pour les scripts d'imports/exports réguliers ?
